spring:
  application:
    name: hackathon
  server:
    port: 8080
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true
springdoc:
  use-fqn: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  cache:
    disabled: true


oauth:
  kakao:
    client-id: 4870a2ee1639568628ea3e9351ab0155
    redirect-uri: http://localhost:8080/auth/kakao/callback

jwt:
  secret: Lun7qvfZd1o6UvvdpE9eKB/qkDZzdTYwNI9TMIoj0iI=
  expiration: 3600000 # ?
