spring:
  datasource:
    url: jdbc:mysql://hackthon-server-db-v.cwmf5niftwns.ap-northeast-2.rds.amazonaws.com:3306/hackthon_db?serverTimezone=Asia/Seoul
    username: admin
    password: hackthon
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

server:
  port: 8080

oauth:
  kakao:
    client-id: 4870a2ee1639568628ea3e9351ab0155
    redirect-uri: http://localhost:8080/auth/kakao/callback

jwt:
  secret: Lun7qvfZd1o6UvvdpE9eKB/qkDZzdTYwNI9TMIoj0iI=
  expiration: 3600000 # ?